let promptData = {
    "スタイル": {
        "品質": {
            "高品質": "high quality",
            "傑作": "masterpiece",
            "精細ウルトラ": "ultra detailed",
            "高解像度": "highres",
            "4K": "4k",
            "8K": "8k",
            "光沢": "luster",
            "超絶技巧イラスト": "super fine illustration",
            "豊富なカラーバリエーション": "wide range of color variations",
            "美しい色彩": "beautiful color rendering",
            "忠実な色再現": "accurate color reproduction",
            "自然な色合い": "natural color tones",
            "美しいグラデーション": "beautiful gradients",
            "シャープな描写": "sharp rendering",
            "鮮明な線画": "crisp lines",
            "立体感のある表現": "3-dimensional expression",
            "リアルな質感": "realistic texture",
            "滑らかな曲線": "smooth curves"
        },
        "画風": {
            "ファンタジー": "fantasy paintings",
            "サイバーパンク": "cyberpunk painting",
            "ホラー": "horror painting",
            "ＳＦ": "Science Fiction paintings",
            "ミリタリー": "Military paintings",
            "3Ｄ": "3D render",
            "イラスト": "illustration",
            "線画": "line art",
            "油彩": "oil painting",
            "水彩画": "watercolor painting",
            "公式アート": "official art",
            "製品アート": "production art",
            "小説の挿絵": "novel illustration",
            "アニメ": "anime",
            "写真": "photograph",
            "リアルな": "hyper realistic",
            "モノクロ": "monochromatic",
            "ゴシック": "gothic",
            "シンプル": "simple art",
            "カートゥーン": "cartoon art",
            "ミニマリズム": "minimalistic art",
            "ポップアート": "pop art",
            "抽象画": "abstract art",
            "シュールレアリズム": "surrealism",
            "モダンアート": "modern art",
            "ビジュアルノベル": "visual novel art",
            "和風画": "Japanese-style painting",
            "漫画": "comic art",
            "グラフィティ": "graffiti art",
            "タイポグラフィ": "typography art",
            "コンセプトアート": "concept art",
            "映画ポスター": "movie poster art",
            "ファッションイラスト": "fashion illustration",
            "ゲームイラスト": "game illustration",
            "ビジネスアート": "business art",
            "写実的な": "realistic",
            "レトロ": "retro style",
            "実験的な": "experimental",
            "アートデコ": "Art Deco",
            "ノワール": "film noir",
            "コミカル": "comical",
            "アンティーク": "antique style",
            "ダークファンタジー": "dark fantasy",
            "ビジョンアート": "visionary art",
            "ストリートアート": "street art",
            "エレガント": "elegant",
            "アバンギャルド": "avant-garde",
            "ポータルファンタジー": "portal fantasy",
            "ヴィンテージ": "vintage style",
            "キュビズム": "cubism",
            "フォトリアリズム": "photorealism",
            "フューチャリスティック": "futuristic",
            "レトロフューチャー": "retro-futuristic",
            "ユートピア": "utopian",
            "ディストピア": "dystopian",
            "メルヘン": "fairy tale",
            "ワンダーランド": "wonderland",
            "スチームパンク": "steampunk",
            "ポストアポカリプス": "post-apocalyptic"
        }
    },
    "人物": {
        "役職": {
            "男の子": "boy",
            "男の子複数人": "multiple boys",
            "女の子": "girl",
            "女の子複数人": "multiple girls",
            "ソロ": "solo",
            "子ども": "child",
            "子ども複数人": "multiple children",
            "男性": "man",
            "男性複数人": "multiple men",
            "女性": "woman",
            "女性複数人": "multiple women",
            "エレガントな女性": "elegant woman",
            "カップル": "couple",
            "夫婦": "wife and husband",
            "学生": "student",
            "先生": "teacher",
            "看護師": "nurse",
            "医師": "doctor",
            "ビジネスマン": "businessman",
            "ビジネスウーマン": "businesswoman",
            "芸術家": "artist",
            "アイドル": "idol",
            "スポーツ選手": "athlete",
            "料理人": "cook",
            "俳優": "actor",
            "女優": "actress",
            "モデル": "model",
            "巫女": "shrine maiden",
            "忍者": "ninja",
            "騎士": "knight",
            "王子": "prince",
            "王女": "princess",
            "赤ちゃん": "baby",
            "老人": "elderly person",
            "アニメキャラクター": "anime character",
            "マスコットキャラクター": "mascot character",
            "架空の人物": "fictional character",
            "歴史上の人物": "historical figure"
        },
        "年齢": {
            "大人": "adult",
            "子供": "child",
            "若者": "youth",
            "若い": "young",
            "10代": "teenager",
            "二十歳": "Twenties",
            "三十歳": "Thirties",
            "四十歳": "Forties",
            "五十歳": "Fifties",
            "六十歳": "Sixties",
            "七十歳": "Seventies",
            "八十歳": "Eighties",
            "九十歳": "Nineties",
            "百歳以上": "Centenarian"
        }
    },
    "感情": {
        "性格": {},
        "愛情": {
            "愛": "Love",
            "愛おしい": "Adorable",
            "恋に落ちた顔": "face fallen in love",
            "溺愛": "doting",
            "甘える": "pamper",
            "甘い微笑み": "sweet smile",
            "ヤンデレ": "Yandere",
            "優しい微笑み": "gentle smile",
            "恋い焦がれた表情": "longing look"
        },
        "笑顔": {
            "笑顔": "smile",
            "笑う": "laugh",
            "優しい笑み": "gentle smile",
            "魅惑的な笑顔": "seductive smile",
            "満面の笑み": "smiling broadly",
            "ハッピー": "happy",
            "ドヤ顔": "doyagao",
            "ニヤニヤ": "grin",
            "ニヤニヤ2": "smirk",
            "爆笑": "burst out laughing",
            "苦笑い": "wry smile",
            "微笑": "smiling gently",
            "上品な笑顔": "elegant smile",
            "自然な笑顔": "natural smile",
            "にっこり": "smiling sweetly",
            "ニヤリ": "sly smile",
            "はにかむ笑顔": "bashful smile",
            "ウインクと笑顔": "wink and smile",
            "人懐っこい笑顔": "friendly smile",
            "にやりと笑う": "grin mischievously",
            "楽しそうな笑顔": "joyful smile",
            "物思いにふける笑顔": "thoughtful smile",
            "自信にあふれる笑顔": "confident smile",
            "驚きの笑顔": "surprised smile",
            "満足げな笑顔": "satisfied smile",
            "甘い笑顔": "sweet smile",
            "真剣な笑顔": "serious smile",
            "静かな笑顔": "quiet smile",
            "明るい笑顔": "bright smile",
            "輝く笑顔": "radiant smile",
            "憂いを含んだ笑顔": "smile tinged with sadness",
            "嬉しそうな笑顔": "pleased smile",
            "寛容な笑顔": "tolerant smile",
            "爽やかな笑顔": "refreshing smile",
            "純真な笑顔": "innocent smile",
            "照れ笑い": "blushing smile",
            "緊張した笑い": "strained laugh"
        },
        "恥": {
            "恥ずかしい": "embarrassed",
            "赤面": "blush",
            "赤面鼻": "nose blush",
            "赤面顔全体": "full-face blush",
            "顔を隠す": "hiding face",
            "目を伏せる": "looking down in shame",
            "手で口を覆う": "covering mouth with hand in embarrassment",
            "体を隠す": "covering body in embarrassment",
            "ぎこちなく笑う": "awkwardly laughing",
            "照れ笑い": "self-conscious smile",
            "恥じらいの微笑み": "bashful smile"
        },
        "怒り": {
            "怒り": "anger",
            "怒る": "to get angry",
            "激怒": "rage",
            "怒り顔": "angry face",
            "怒鳴る": "to shout in anger",
            "拳を握る": "clenching fists in anger",
            "目を充血させる": "eyes turning red with anger",
            "怒りで震える": "trembling with anger",
            "冷静さを失う": "losing one's cool"
        },
        "嫌悪": {
            "嫌悪": "disgust",
            "嫌な顔をする": "making a disgusted face",
            "むかつく": "to feel nauseated",
            "吐き気を催す": "feeling sick to one's stomach",
            "不機嫌な表情": "sour expression",
            "鼻をつく": "scrunching nose in disgust",
            "手で口を押さえる": "covering mouth in disgust",
            "嫌悪感をあらわにする": "showing visible signs of disgust",
            "胃が煮えくり返る": "stomach churning with disgust"
        },
        "驚き": {
            "驚き": "surprise",
            "びっくり": "startled",
            "驚く": "to be surprised",
            "驚きの表情": "expression of surprise",
            "目を丸くする": "eyes widening in surprise",
            "口をあんぐり": "mouth opening in surprise",
            "声を上げる": "shouting in surprise",
            "呆然とする": "stunned",
            "驚愕": "astonishment"
        },
        "悲しい": {
            "悲しい": "sad",
            "泣く": "crying",
            "涙を流す": "tearful",
            "嘆き": "grief",
            "慟哭": "wailing",
            "哀しみ": "sorrow",
            "涙目": "teary-eyed",
            "涙ぐむ": "tear up",
            "顔を伏せる": "face down",
            "うつろな目": "vacant eyes"
        },
        "顔文字": {
            ":)": ":)",
            "O:)": "O:)",
            ":3": ":3",
            "=3": "=3",
            ":D": ":D",
            "=D": "=D",
            "XD": "XD",
            ":P": ":P",
            ":þ": ":þ",
            "XP": "XP",
            ":(": ":(",
            ":<": ":<",
            ":[": ":[",
            ":O": ":O",
            ":@": ":@",
            "X(": "X(",
            ":v": ":v",
            ":/": ":/"
        }
    },
    "顔": {
        "顔の特徴": {
            "細顔": "slender face",
            "丸顔": "round face",
            "童顔": "baby face",
            "きめ細やかな肌": "super detailed skin",
            "美しい顔": "detailed beautiful face",
            "美しい顔と目": "detailed beautiful face and eyes",
            "表情豊かな顔": "expressive face",
            "個性的な顔": "distinctive face",
            "シャープな顔立ち": "sharp features",
            "柔らかな顔立ち": "soft features",
            "陰影が豊かな顔": "richly shaded face",
            "自然な顔": "natural looking face",
            "洗練された顔": "sophisticated face",
            "透き通った肌": "clear translucent skin",
            "小さな顔": "small face",
            "大きな顔": "large face",
            "バランスの取れた顔": "well-balanced face",
            "ユニークな顔": "unique face",
            "年齢に合った顔": "age-appropriate face",
            "似顔絵風の顔": "cartoon-like face",
            "和風の顔": "Japanese-style face",
            "洋風の顔": "Western-style face",
            "3D風の立体感ある顔": "3D-looking face",
            "リアルな顔": "hyper realistic face"
        },
        "目": {
            "閉じた目": "closed eyes",
            "ジト目": "jitome",
            "たれ目": "tareme",
            "ツリ目": "tsurime",
            "睨み": "glaring",
            "上目づかい": "upturned eyes",
            "ハートの目": "heart shaped eyes",
            "キラキラな瞳": "sparkling eyes",
            "オッドアイ": "heterochromia",
            "泣き目": "tearful eyes",
            "笑い目": "smiling eyes",
            "怒り目": "angry eyes",
            "困り目": "perplexed eyes",
            "驚き目": "surprised eyes",
            "閃く瞳": "shining eyes",
            "長いまつ毛": "long eyelashes"
        },
        "目色": {
            "青い目": "blue eyes",
            "緑の目": "green eyes",
            "茶色の目": "brown eyes",
            "灰色の目": "gray eyes",
            "アンバーの目": "amber eyes",
            "ヘーゼルの目": "hazel eyes",
            "紫の目": "purple eyes",
            "赤い目": "red eyes",
            "金色の目": "golden eyes",
            "銀色の目": "silver eyes",
            "水色の目": "aquamarine eyes",
            "琥珀色の目": "topaz eyes",
            "深紅の目": "crimson eyes",
            "紺色の目": "navy eyes",
            "ピンク色の目": "pink eyes",
            "オレンジ色の目": "orange eyes",
            "黄色い目": "yellow eyes",
            "白い目": "white eyes"
        },
        "口": {
            "閉じた口": "closed mouth",
            "開いた口": "open mouth",
            "半開きの口": "half-open mouth",
            "歯を見せた口": "smiling with teeth",
            "食いしばった歯": "clenched teeth",
            "笑っている口": "laughing",
            "唇を噛む": "biting lips",
            "口を尖らせる": "pursed lips",
            "口をとがらせる": "grimacing",
            "口を横に引く": "smirking",
            "口角を上げる": "upturned mouth corners",
            "口角を下げる": "downturned mouth corners",
            "口笛を吹く": "whistling",
            "口をつぐむ": "mouth shut",
            "口を開けっ放し": "mouth agape",
            "唇を舐める": "licking lips",
            "口をとがらせてにやりと笑う": "smirking with a sneer"
        },
        "耳": {
            "猫耳": "cat ears",
            "ウサギ耳": "rabbit ears",
            "エルフ": "pointy ears",
            "三角形の耳": "triangular ears",
            "長い耳": "long ears",
            "短い耳": "short ears",
            "ふさふさの耳": "fluffy ears",
            "垂れ耳": "droopy ears",
            "立ち耳": "upright ears",
            "耳たぶ": "earlobe"
        }
    },
    "髪": {
        "ヘアスタイル": {
            "ポニーテール": "ponytail",
            "ツインテール": "twin tail",
            "ツーブロック": "two blocks",
            "ショート": "short hair",
            "ボブ": "bob hair",
            "ミディアム": "medium hair",
            "セミロング": "Semi-long hair",
            "ロング": "long hair",
            "スーパーロング": "super long hair",
            "ストレート": "straight hair",
            "ウェーブ": "wavy hair",
            "カール": "curly hair",
            "パーマ": "permed hair",
            "ヘアカラー": "hair color",
            "グラデーションカラー": "gradient hair color",
            "ハイライト": "highlighted hair",
            "ローライト": "lowlighted hair",
            "ハーフアップ": "half up hair",
            "三つ編み": "Braid hair",
            "三つ編み小": "small braid",
            "三つ編み大": "large braid",
            "フィッシュボーン": "fishbone braid",
            "ドリル": "drill hair",
            "アホ毛": "antenna hair",
            "エクステ": "hair extension",
            "ウィッグ": "wig",
            "かつら": "toupee",
            "濡れた髪": "wet hair",
            "乱れた髪": "disheveled hair",
            "片目を覆う髪": "hair covering one eye",
            "前髪": "bangs",
            "水平にカットされた髪": "blunt bangs",
            "額の横で分けられた髪": "side bang"
        },
        "ヘアカラー": {
            "金髪": "Blonde hair",
            "赤髪": "Red hair",
            "茶髪": "Brown hair",
            "黒髪": "Black hair",
            "灰髪": "Gray hair",
            "白髪": "White hair",
            "青髪": "Blue hair",
            "緑髪": "Green hair",
            "紫髪": "Purple hair",
            "ピンク髪": "Pink hair",
            "オレンジ髪": "Orange hair",
            "シルバー髪": "Silver hair",
            "ベージュ髪": "Beige hair"
        }
    },
    "体": {
        "胸": {
            "巨乳": "large breasts",
            "胸の谷間": "cleavage",
            "貧乳": "small breasts",
            "平らな胸": "flat chest",
            "谷間からの視線": "glancing at cleavage",
            "胸元": "chest area",
            "胸ポケット": "breast pocket",
            "胸の揺れ": "breast bounce",
            "胸元が開いた服": "low-cut clothing",
            "へそ": "navel"
        },
        "汗": {
            "汗": "sweat",
            "肌に光沢": "shiny skin",
            "汗だく": "drenched in sweat",
            "汗がしたたる": "droplets of sweat",
            "汗の滴": "sweat drops",
            "汗が垂れる": "sweat dripping",
            "汗ばむ": "feeling sweaty",
            "汗をぬぐう": "wiping off sweat",
            "濡れた": "wet",
            "髪が汗でべとつく": "sweaty hair",
            "シャツが汗で濡れる": "sweat stains on shirt",
            "汗で洋服がくっつく": "clothes sticking to skin due to sweat"
        }
    },
    "方向": {
        "目線": {
            "こちらを向く": "looking at viewer",
            "見上げる": "looking up",
            "見下ろす": "looking down",
            "振り返り見る": "looking back",
            "視線をそらす": "looking away",
            "首を傾ける": "head tilt",
            "横目": "sidelong glance",
            "見つめる": "gazing",
            "瞑る": "closing eyes gently",
            "キョロキョロする": "looking around",
            "真剣な目つき": "serious gaze",
            "笑顔で見る": "looking with a smile",
            "じっと見つめる": "staring intently",
            "微笑みながら見る": "looking with a smile",
            "興味津々と見る": "looking with curiosity",
            "まばたきする": "blinking",
            "おどけた目つき": "playful gaze",
            "驚きの表情で見る": "looking with a surprised expression",
            "眉をひそめて見る": "looking with a frown",
            "うっとりと見る": "looking with fascination"
        },
        "向き": {
            "上から": "from above",
            "下から": "from below",
            "下から見上げる": "looking up from below",
            "横から": "from the side",
            "後ろから": "from behind",
            "まっすぐに": "straight-on",
            "全身": "full body",
            "顔": "face",
            "横顔": "profile",
            "上半身": "upper body",
            "斜め上から": "from diagonally above",
            "斜め下から": "from diagonally below",
            "前から": "from the front",
            "後ろから見る": "viewed from behind",
            "横から見る": "viewed from the side",
            "斜め前から": "from diagonally in front",
            "正面から見上げる": "looking up from the front",
            "正面から見下ろす": "looking down from the front",
            "背後から見上げる": "looking up from behind",
            "背後から見下ろす": "looking down from behind",
            "側面から見上げる": "looking up from the side",
            "側面から見下ろす": "looking down from the side"
        }
    },
    "ポーズ": {
        "全体のポーズ": {
            "寝姿": "sleeping pose",
            "睡眠": "sleeping",
            "眠い": "sleepy",
            "自撮り": "selfie",
            "泳ぐ": "swimming",
            "ピースサイン": "peace sign",
            "抱きしめる": "hugging",
            "座る": "sit",
            "しゃがむ": "squat",
            "ジャンプ": "jumping",
            "頭を近づける": "heads together",
            "顔を寄せる": "face to face",
            "頬を寄せる": "cheek to cheek",
            "身体を寄せる": "hug",
            "後からハグする": "hug from behind",
            "膝を抱える": "hugging knees",
            "正座": "seiza",
            "前かがみ": "leaning forward",
            "胸を張る": "stretches chest",
            "ひざまずく": "kneel down"
        },
        "ポーズ_腕": {
            "腕を組む": "crossed arms",
            "腕を伸ばす": "stretch your arms",
            "手を上げる": "hand up",
            "両手を広げる": "spread arms",
            "腕を後ろに回す": "arms behind back",
            "腕を頭の後ろに": "arm behind the head",
            "猫の手": "paw pose",
            "手を振る": "waving hand",
            "肘をつく": "resting on elbow",
            "手を組む": "folded hands",
            "手を握る": "holding hands",
            "手を合わせる": "prayer pose",
            "拳を突き上げる": "fist pump",
            "拳を握る": "clenched fists",
            "手を広げる": "open arms",
            "手を挙げる": "raising hand",
            "手を引く": "pulling hand",
            "手を伸ばす": "reaching out",
            "手を招く": "beckoning hand",
            "手を添える": "resting hand",
            "手を放す": "letting go",
            "手を口元に当てる": "hand over mouth",
            "手を耳に当てる": "hand to ear",
            "手を顔に当てる": "hand on face",
            "手を腰に当てる": "hand on hip",
            "手を胸に当てる": "hand on chest",
            "手を口に当てる": "hand on mouth",
            "指を差す": "pointing finger",
            "指でつまむ": "pinching gesture"
        },
        "ポーズ_足": {
            "片脚を上げる": "leg up",
            "足を組む": "cross one's legs",
            "足を伸ばす": "stretch your legs",
            "足を広げる": "spread your legs",
            "膝を立てて": "knees up"
        }
    },
    "服装": {
        "服": {
            "スーツ": "suit",
            "浴衣": "yukata",
            "着物": "kimono",
            "和服": "Japanese clothes",
            "水着": "swimsuit",
            "ビキニ": "bikini",
            "看護師": "nurse",
            "修道士": "nun",
            "バニーガール": "playboy bunny",
            "メイド服": "maid",
            "軍服": "military uniform",
            "ジャージ": "sweatsuit",
            "タキシード": "tuxedo",
            "ドレス": "dress"
        },
        "服_ジャンル": {
            "カジュアル": "casual clothes",
            "フォーマル": "formal attire",
            "スポーティ": "sporty clothes",
            "ボヘミアン": "bohemian outfit",
            "レトロ": "retro outfit",
            "エレガント": "elegant outfit",
            "ゴシック": "gothic outfit",
            "モード": "fashionable clothes"
        },
        "服_学校": {
            "学生服": "school uniform",
            "ブレザー": "blazer",
            "セーラー服": "sailor uniform",
            "セーラー襟": "sailor collar",
            "スクール水着": "school swimsuit",
            "タイツ": "school tights",
            "カーディガン": "school cardigan",
            "合唱団": "choir uniform",
            "エプロン": "school apron",
            "靴下": "school knee-high socks",
            "ネクタイ": "tie",
            "ワイシャツ": "white shirt",
            "スカート": "skirt",
            "ズボン": "pants",
            "シューズ": "school shoes",
            "リボン": "ribbon",
            "ベルト": "belt",
            "ブラウス": "blouse",
            "セーター": "sweater",
            "ジャンパー": "jumper",
            "ジャージ": "track suit",
            "ローファー": "loafers",
            "スニーカー": "sneakers"
        },
        "服_スポーツ": {
            "バレーボール": "volleyball uniform",
            "サッカー": "soccer uniform",
            "野球": "baseball uniform",
            "ダンスチーム": "dance team uniform",
            "陸上競技": "track and field",
            "バスケットボール": "basketball uniform",
            "スポーツ": "sports uniform",
            "チアリーディング": "cheerleading uniform",
            "水泳": "swim team uniform",
            "テニス": "tennis uniform",
            "柔道": "judo uniform",
            "剣道": "kendo uniform",
            "合気道": "aikido uniform",
            "空手": "karate uniform",
            "バドミントン": "badminton uniform",
            "卓球": "table tennis uniform",
            "ボクシング": "boxing uniform",
            "ウエイトリフティング": "weightlifting uniform",
            "ソフトボール": "softball uniform",
            "ラグビー": "rugby uniform",
            "ハンドボール": "handball uniform",
            "フェンシング": "fencing uniform",
            "アーチェリー": "archery uniform"
        },
        "トップス": {
            "シャツ": "shirt",
            "ブラウス": "blouse",
            "ドレスシャツ": "dress shirt",
            "セーター": "sweater",
            "チュニック": "tunic",
            "ベスト": "vest",
            "タンクトップ": "tank top",
            "キャミソール": "camisole",
            "ベアトップ": "bare top",
            "ブラトップ": "bra top"
        },
        "ジャケット": {
            "デニムジャケット": "Denim Jacket",
            "ミリタリージャケット": "military jacket",
            "ライダースジャケット": "riders jacket",
            "テーラードジャケット": "tailored jacket",
            "レザージャケット": "leather jacket",
            "スタジャン": "varsity jacket",
            "ナイロンジャケット": "nylon jacket",
            "ダウンジャケット": "Down jacket",
            "カーディガン": "cardigan"
        },
        "コート": {
            "Pコート": "pea coat",
            "チェスターコート": "chester coat",
            "ノーカラーコート": "collarless coat",
            "トレンチコート": "trench coat",
            "ダッフルコート": "duffle coat",
            "ボアコート": "boa coat",
            "カーコート": "car coat",
            "ダウンコート": "down coat",
            "パッド入りコート": "padded coat",
            "ショートコート": "short coat",
            "ロングコート": "long coat",
            "モッズコート": "mod coat",
            "ベルト付きコート": "belted coat"
        },
        "ワンピース": {
            "シャツワンピース": "shirt dress",
            "ニットワンピース": "knit dress",
            "カシュクールワンピース": "cache-coeur dress",
            "ティアードワンピース": "tiered dress",
            "パーカーワンピース": "hoodie dress",
            "サロペット": "salopette dress",
            "デニムワンピース": "denim dress",
            "フリルワンピース": "frill dress",
            "シースルーワンピース": "see-through dress",
            "シンプルワンピース": "simple dress",
            "レースワンピース": "lace dress",
            "フラワーワンピース": "flower dress",
            "ボレロワンピース": "bolero dress",
            "タイトワンピース": "tight dress",
            "オフショルワンピース": "off-shoulder dress",
            "キャミワンピース": "camisole dress",
            "ビスチェワンピース": "bustier dress",
            "マキシワンピース": "maxi dress",
            "ミニワンピース": "mini dress"
        },
        "ボトムス": {
            "ジーンズ": "jeans",
            "ベイカーパンツ": "baker pants",
            "ワイドパンツ": "wide pants",
            "テーパードパンツ": "tapered pants",
            "スキニーパンツ": "skinny pants",
            "カーゴパンツ": "cargo pants",
            "レギンス": "leggings",
            "レースタイツ": "lace tights",
            "ストッキング": "stockings",
            "サロペット": "salopette",
            "ショートパンツ": "shorts",
            "チノパン": "chino pants",
            "レザーパンツ": "leather pants",
            "デニムショートパンツ": "denim shorts",
            "ハーフパンツ": "half pants",
            "キュロットスカート": "culottes"
        },
        "スカート": {
            "フレアスカート": "flare skirt",
            "プリーツスカート": "pleated skirt",
            "タイトスカート": "tight skirt",
            "フィッシュテールスカート": "fishtail skirt",
            "ラップスカート": "wrap skirt",
            "レーススカート": "lace skirt",
            "ミニスカート": "mini skirt",
            "マキシスカート": "maxi skirt",
            "デニムスカート": "denim skirt",
            "フリルスカート": "frill skirt",
            "シースルースカート": "sheer skirt",
            "ボリュームスカート": "volume skirt",
            "チュールスカート": "tulle skirt",
            "レザースカート": "leather skirt"
        }
    },
    "装飾": {
        "全体の装飾": {
            "リボン": "ribbon",
            "宝石": "jewelry",
            "帽子": "hat",
            "帽子リボン": "hat ribbon",
            "ヘアバンド": "hairband",
            "ヘアクリップ": "hair clip",
            "角": "horns",
            "花": "hair flower",
            "ヘッドフォン": "headphones",
            "天使の輪": "halo",
            "カチューシャ": "headband",
            "眼鏡": "glasses",
            "サングラス": "sunglasses",
            "イヤリング": "earrings",
            "ピアス": "piercing",
            "首輪": "choker",
            "ネックレス": "necklace",
            "リボンヘアゴム": "ribbon hair tie",
            "バレッタ": "barrette",
            "ヘアピン": "hairpin",
            "ヘアアクセサリー": "hair accessory",
            "ティアラ": "tiara",
            "キャップ": "cap",
            "スカーフ": "scarf",
            "マフラー": "muffler",
            "フード": "hood",
            "マスク": "mask",
            "ヘアーバンド": "head wrap",
            "ハット": "hat",
            "ヘッドピース": "headpiece",
            "かんざし": "ornamental hairpin",
            "ヘアチョーク": "hair chalk",
            "ベール": "veil",
            "ヘアネット": "hairnet",
            "カチューシャリボン": "headband ribbon",
            "ヘアスティック": "hair stick",
            "フラワークラウン": "flower crown",
            "シルクヘアスカーフ": "silk hair scarf",
            "ビーニー": "beanie",
            "ボンネット": "bonnet",
            "ヘアフラワーピン": "hair flower pin",
            "ヘアターバン": "hair turban",
            "ヘッドチェーン": "head chain",
            "ヘッドスカーフ": "headscarf"
        },
        "翼": {
            "翼": "wings",
            "悪魔の翼": "evil wings",
            "コウモリの翼": "bat wings",
            "天使の翼": "angel wings",
            "ドラゴンの翼": "dragon wings",
            "蝶の翼": "butterfly wings",
            "鳥の翼": "bird wings",
            "漆黒の翼": "jet black wings",
            "フェニックスの翼": "phoenix wings",
            "ペガサスの翼": "pegasus wings",
            "雷鳥の翼": "thunderbird wings",
            "翼の生えた人間": "winged human",
            "魔法の翼": "magical wings",
            "羽根の翼": "feathered wings",
            "羽ばたく翼": "flapping wings",
            "飛行の翼": "flight wings",
            "羽の翼": "plumed wings",
            "鷲の翼": "eagle wings",
            "翼を広げる": "spread wings",
            "翼を持つ": "have wings"
        },
        "手": {
            "手袋": "gloves",
            "長い手袋": "elbow gloves",
            "指なし手袋": "fingerless gloves",
            "手首飾り": "bracelet",
            "リング": "ring",
            "腕輪": "bangle",
            "手袋つきストッキング": "gloved stockings",
            "指輪": "ring",
            "手の刺青": "hand tattoo",
            "手甲": "gauntlet",
            "手の鎖": "hand chain",
            "指輪付きハンドチェーン": "ring hand chain",
            "指切りグローブ": "cutout gloves",
            "手のビーズブレスレット": "beaded bracelet",
            "手のチャームブレスレット": "charm bracelet",
            "手のレースグローブ": "lace gloves",
            "手のリストレット": "wristlet",
            "手袋付きマフラー": "gloved scarf",
            "手首ウォーマー": "wrist warmers",
            "手の羽飾り": "feathered hand accessory",
            "指のリング": "finger ring",
            "手のカフリンクス": "cufflinks",
            "手袋付きアームウォーマー": "gloved arm warmers",
            "手のビーズリング": "beaded ring",
            "手の花飾り": "flower decoration for hand"
        },
        "腰": {
            "ベルト": "belt",
            "しっぽ": "tail",
            "猫のしっぽ": "cat tail",
            "狐のしっぽ": "fox tail",
            "ポーチ": "pouch",
            "サスペンダー": "suspenders",
            "ホルスター": "holster"
        },
        "足": {
            "パンスト": "pantyhose",
            "ニーソックス": "Thighhighs",
            "ガーターストラップ": "garter straps",
            "太ももまでのブーツ": "thigh boots",
            "ハイヒール": "high heels",
            "ブーツ": "boots"
        }
    },
    "背景": {
        "空": {
            "空": "sky",
            "青空": "blue sky",
            "晴れ": "sunny",
            "太陽の光": "sunlight",
            "雲のある空": "cloud",
            "曇った空": "cloudy sky",
            "朝焼け": "morning glow",
            "夕焼け": "sunset glow",
            "赤い空": "red sky",
            "虹": "rainbow",
            "雨の空": "rainy sky",
            "雷雲": "thundercloud",
            "積乱雲": "cumulonimbus"
        },
        "夜空": {
            "夜空": "night sky",
            "美しい星空": "beautiful starry sky",
            "満天の星空": "sky full of stars",
            "月": "moon",
            "満月": "full moon",
            "三日月": "crescent moon",
            "星空": "starry sky",
            "流れ星": "shooting star",
            "天の川": "Milky Way",
            "月明かり": "moonlight",
            "街の夜景": "city night view",
            "花火": "fireworks",
            "オーロラ": "aurora"
        },
        "時間": {
            "朝": "morning",
            "昼": "noon",
            "晩": "night",
            "夜": "midnight",
            "深夜": "late night",
            "夜明け": "dawn",
            "日没": "sunset",
            "日の出": "sunrise",
            "正午": "midday",
            "夕暮れ": "dusk",
            "黄昏": "twilight",
            "夕方": "evening"
        },
        "光": {
            "自然な陰影": "natural shading",
            "ハイライトの表現": "highlight rendering",
            "ソフトな光の表現": "soft lighting",
            "ハードな光の表現": "hard lighting",
            "スポットライト効果": "spotlight effect",
            "レンズフレア": "lens flare",
            "ブルーム効果": "bloom effect",
            "グロー効果": "glow effect",
            "影の表現": "shadow rendering",
            "光の拡散": "light diffusion",
            "光の反射": "light reflection",
            "反射光の表現": "reflected light rendering",
            "逆光の表現": "backlight rendering",
            "夕日の表現": "sunset rendering",
            "月明かりの表現": "moonlight rendering",
            "電光板の表現": "neon sign rendering",
            "炎の表現": "flame rendering"
        },
        "家": {
            "ベッド": "bed",
            "寝室": "bedroom",
            "庭": "garden",
            "キッチン": "kitchen",
            "ダイニングルーム": "dining room",
            "リビングルーム": "living room",
            "トイレ": "toilet",
            "お風呂": "bathroom",
            "玄関": "entrance",
            "廊下": "corridor",
            "階段": "stairs",
            "屋根裏部屋": "attic",
            "地下室": "basement",
            "洗面所": "washroom",
            "書斎": "study",
            "ロフト": "loft",
            "ガレージ": "garage",
            "ベランダ": "balcony",
            "テラス": "terrace"
        },
        "自然": {
            "自然": "nature",
            "砂漠": "desert",
            "丘": "on a hill",
            "山": "mountain",
            "岩": "rock",
            "草原": "grass field",
            "森の中": "in the forest",
            "紅葉の森": "autumn leaves forest",
            "桜": "cherry blossoms",
            "花": "flower"
        },
        "水辺": {
            "水路": "canal",
            "川": "river",
            "滝": "waterfall",
            "海": "sea",
            "ビーチ": "beach",
            "湖": "lake",
            "湖畔": "lake shore",
            "橋": "bridge",
            "港": "port",
            "岸辺": "shore",
            "浜辺": "shoreline",
            "干潟": "tidal flat",
            "船": "boat",
            "クルーズ船": "cruise ship",
            "ヨット": "yacht"
        },
        "街": {
            "街": "town",
            "道": "road",
            "住宅街": "residential street",
            "街並み": "cityscape",
            "商店街": "shopping street",
            "地下街": "underground mall",
            "風車": "windmill",
            "ビル": "building",
            "タワー": "tower"
        },
        "お店": {
            "レストラン": "restaurant",
            "コーヒーショップ": "coffee shop",
            "ティーショップ": "tea shop",
            "デパート": "department store",
            "ショッピングモール": "mall",
            "マーケット": "market",
            "ナイトマーケット": "night market",
            "クリスマスマーケット": "christmas market",
            "花屋": "flower shop",
            "パン屋": "bakery",
            "菓子屋": "sweet shop",
            "ジュースバー": "juice bar",
            "バー": "bar",
            "居酒屋": "izakaya",
            "スナック": "snack bar",
            "クラブ": "club"
        },
        "公共": {
            "学校": "school",
            "教室": "classroom",
            "廊下": "hallway",
            "プール": "pool",
            "病院": "hospital",
            "教会": "church",
            "図書館": "library",
            "公園": "park",
            "映画館": "movie theater",
            "博物館": "museum",
            "キャンプ場": "campsite",
            "温泉": "onsen",
            "水族館": "aquarium",
            "電車内": "on the train",
            "神社": "shrine",
            "研究室": "laboratory",
            "刑務所": "prison",
            "美術館": "art museum",
            "劇場": "theater",
            "コンサートホール": "concert hall",
            "オペラハウス": "opera house",
            "運動場": "playground",
            "競技場": "sports ground",
            "空港": "airport",
            "駅": "train station",
            "バス停": "bus stop",
            "タクシー乗り場": "taxi stand",
            "地下鉄駅": "subway station",
            "トンネル": "tunnel",
            "橋": "bridge",
            "トンネル内": "in a tunnel",
            "エレベーター": "elevator",
            "エスカレーター": "escalator",
            "階段": "stairs",
            "トイレ": "restroom",
            "コインロッカー": "coin locker",
            "駐車場": "parking lot",
            "ガソリンスタンド": "gas station",
            "自動販売機": "vending machine",
            "交差点": "intersection",
            "横断歩道": "pedestrian crossing"
        },
        "都市": {
            "東京": "tokyo",
            "京都": "kyoto",
            "大阪": "osaka",
            "札幌": "sapporo",
            "名古屋": "nagoya",
            "沖縄": "okinawa",
            "ニューヨーク": "newyork",
            "パリ": "paris",
            "ロンドン": "london",
            "上海": "shanghai",
            "香港": "hong kong",
            "シカゴ": "chicago",
            "ベルリン": "berlin",
            "シドニー": "sydney",
            "バルセロナ": "barcelona",
            "アムステルダム": "amsterdam",
            "ベネチア": "venice",
            "ケアンズ": "cairns",
            "ダブリン": "dublin",
            "イスタンブール": "istanbul",
            "トロント": "toronto",
            "モスクワ": "moscow",
            "ワシントンDC": "washington dc",
            "ソウル": "seoul",
            "バンコク": "bangkok",
            "ドバイ": "dubai",
            "ロサンゼルス": "los angeles",
            "サンフランシスコ": "san francisco",
            "シアトル": "seattle",
            "マイアミ": "miami",
            "ラスベガス": "las vegas",
            "ヒューストン": "houston",
            "メルボルン": "melbourne",
            "バンクーバー": "vancouver",
            "モントリオール": "montreal",
            "サンパウロ": "sao paulo",
            "リオデジャネイロ": "rio de janeiro",
            "メキシコシティ": "mexico city",
            "マドリード": "madrid",
            "ローマ": "rome",
            "フィレンツェ": "florence",
            "アテネ": "athens",
            "ベルファスト": "belfast",
            "エジンバラ": "edinburgh",
            "キャンベラ": "canberra",
            "オークランド": "auckland",
            "クライストチャーチ": "christchurch",
            "ハンブルク": "hamburg",
            "フランクフルト": "frankfurt",
            "ミュンヘン": "munich",
            "チューリッヒ": "zurich",
            "ウィーン": "vienna",
            "ストックホルム": "stockholm",
            "オスロ": "oslo"
        }
    }
}